import {
  CallRecord,
  DashboardMetrics,
  CallVolumeData,
  DetectionDistribution,
  RecentActivityItem,
  EvidenceModule,
  ChunkTimelineItem
} from '../types';

export const mockMetrics: DashboardMetrics = {
  activeCalls: { count: 12, change: '33%', positive: true },
  analyzing: { count: 4, change: '25%', positive: true },
  completed: { count: 87, change: '18%', positive: true },
  needsAttention: { count: 9, change: '50%', positive: false },
};

export const mockCallVolumeData: CallVolumeData[] = [
  { day: 'Sep 12', human: 12, aiGenerated: 9, total: 21 },
  { day: 'Sep 13', human: 15, aiGenerated: 11, total: 26 },
  { day: 'Sep 14', human: 19, aiGenerated: 12, total: 31 },
  { day: 'Sep 15', human: 24, aiGenerated: 13, total: 37 },
  { day: 'Sep 16', human: 18, aiGenerated: 13, total: 31 },
  { day: 'Sep 17', human: 18, aiGenerated: 12, total: 30 },
  { day: 'Sep 18', human: 18, aiGenerated: 17, total: 35 },
];

export const mockDetectionDistribution: DetectionDistribution = {
  totalCalls: 87,
  human: { count: 48, percentage: 55 },
  aiGenerated: { count: 28, percentage: 32 },
  uncertain: { count: 9, percentage: 10 },
  noDecision: { count: 2, percentage: 3 },
};

export const mockLiveCalls: CallRecord[] = [
  {
    callId: 'CALL-1001',
    caller: '+91 98765 43210',
    receiver: 'Demo User',
    duration: '02:14',
    durationSec: 134,
    status: 'ANALYZING',
    latestAnalysis: 'UNCERTAIN',
    decisionStrength: 0.31,
    confidenceStatus: 'PROVISIONAL',
    qualityScore: 0.82,
    conflictLevel: 'MEDIUM',
    createdAt: '2026-09-18T10:22:00Z',
  },
  {
    callId: 'CALL-1002',
    caller: 'Muthu',
    receiver: 'Support Bot',
    duration: '05:32',
    durationSec: 332,
    status: 'ACTIVE',
    latestAnalysis: 'HUMAN',
    decisionStrength: -0.88,
    confidenceStatus: 'CALIBRATED',
    qualityScore: 0.94,
    conflictLevel: 'LOW',
    createdAt: '2026-09-18T10:19:00Z',
  },
  {
    callId: 'CALL-1003',
    caller: '+91 91234 56789',
    receiver: 'Bank Support',
    duration: '00:48',
    durationSec: 48,
    status: 'ANALYZING',
    latestAnalysis: 'AI_GENERATED',
    decisionStrength: 0.84,
    confidenceStatus: 'PROVISIONAL',
    qualityScore: 0.86,
    conflictLevel: 'LOW',
    createdAt: '2026-09-18T10:23:30Z',
  },
  {
    callId: 'CALL-1004',
    caller: 'Priya',
    receiver: 'Insurance',
    duration: '01:27',
    durationSec: 87,
    status: 'CONNECTING',
    latestAnalysis: '--',
    decisionStrength: 0.0,
    confidenceStatus: 'PROVISIONAL',
    qualityScore: 0.65,
    conflictLevel: 'LOW',
    createdAt: '2026-09-18T10:23:00Z',
  },
  {
    callId: 'CALL-1005',
    caller: '+91 90011 22334',
    receiver: 'Unknown',
    duration: '03:11',
    durationSec: 191,
    status: 'ACTIVE',
    latestAnalysis: 'UNCERTAIN',
    decisionStrength: 0.42,
    confidenceStatus: 'PROVISIONAL',
    qualityScore: 0.78,
    conflictLevel: 'HIGH',
    createdAt: '2026-09-18T10:21:00Z',
  },
];

export const mockRecentActivity: RecentActivityItem[] = [
  {
    id: 'act-1',
    callId: 'CALL-1001',
    title: 'New analysis result',
    timeAgo: '2 min ago',
    type: 'analyzing',
  },
  {
    id: 'act-2',
    callId: 'CALL-0998',
    title: 'Completed analysis',
    timeAgo: '12 min ago',
    type: 'completed',
  },
  {
    id: 'act-3',
    callId: 'CALL-0997',
    title: 'Suspicious pattern detected',
    timeAgo: '18 min ago',
    type: 'warning',
  },
  {
    id: 'act-4',
    callId: 'CALL-0996',
    title: 'Analysis in progress',
    timeAgo: '25 min ago',
    type: 'in_progress',
  },
  {
    id: 'act-5',
    callId: 'CALL-0995',
    title: 'Marked as human',
    timeAgo: '32 min ago',
    type: 'human',
  },
];

export const mockCallHistory: CallRecord[] = [
  ...mockLiveCalls,
  {
    callId: 'CALL-0998',
    caller: '+91 98451 12345',
    receiver: 'Financial Advisor',
    duration: '04:12',
    durationSec: 252,
    status: 'COMPLETED',
    latestAnalysis: 'HUMAN',
    decisionStrength: -0.92,
    confidenceStatus: 'CALIBRATED',
    qualityScore: 0.95,
    conflictLevel: 'LOW',
    createdAt: '2026-09-18T10:12:00Z',
  },
  {
    callId: 'CALL-0997',
    caller: 'RoboCaller (Spoofed)',
    receiver: 'Branch Manager',
    duration: '01:05',
    durationSec: 65,
    status: 'COMPLETED',
    latestAnalysis: 'AI_GENERATED',
    decisionStrength: 0.89,
    confidenceStatus: 'CALIBRATED',
    qualityScore: 0.88,
    conflictLevel: 'LOW',
    createdAt: '2026-09-18T10:06:00Z',
  },
  {
    callId: 'CALL-0996',
    caller: '+91 94440 98765',
    receiver: 'Telecom Helpdesk',
    duration: '06:40',
    durationSec: 400,
    status: 'COMPLETED',
    latestAnalysis: 'UNCERTAIN',
    decisionStrength: 0.22,
    confidenceStatus: 'PROVISIONAL',
    qualityScore: 0.72,
    conflictLevel: 'HIGH',
    createdAt: '2026-09-18T09:59:00Z',
  },
  {
    callId: 'CALL-0995',
    caller: 'Anand R.',
    receiver: 'Customer Care',
    duration: '03:15',
    durationSec: 195,
    status: 'COMPLETED',
    latestAnalysis: 'HUMAN',
    decisionStrength: -0.79,
    confidenceStatus: 'CALIBRATED',
    qualityScore: 0.91,
    conflictLevel: 'LOW',
    createdAt: '2026-09-18T09:52:00Z',
  },
  {
    callId: 'CALL-0994',
    caller: 'Automated Loan Agent',
    receiver: 'Card Holder',
    duration: '00:52',
    durationSec: 52,
    status: 'COMPLETED',
    latestAnalysis: 'AI_GENERATED',
    decisionStrength: 0.96,
    confidenceStatus: 'CALIBRATED',
    qualityScore: 0.89,
    conflictLevel: 'LOW',
    createdAt: '2026-09-18T09:44:00Z',
  },
  {
    callId: 'CALL-0993',
    caller: '+91 97890 54321',
    receiver: 'Karthik',
    duration: '02:30',
    durationSec: 150,
    status: 'FAILED',
    latestAnalysis: '--',
    decisionStrength: 0.0,
    confidenceStatus: 'PROVISIONAL',
    qualityScore: 0.32,
    conflictLevel: 'LOW',
    createdAt: '2026-09-18T09:30:00Z',
  }
];

export const mockEvidenceModules: EvidenceModule[] = [
  {
    module: 'wav2vec2',
    name: 'Wav2Vec2 Self-Supervised Acoustic',
    status: 'USED',
    direction: 'SYNTHETIC',
    contribution: 0.34,
    description: 'Neural artifact detection in frame embeddings indicate synthetic waveform reconstruction.'
  },
  {
    module: 'df_arena',
    name: 'DF Arena / AASIST Graph Classifier',
    status: 'USED',
    direction: 'SYNTHETIC',
    contribution: 0.28,
    description: 'Spectral graph convolutional layers identify non-natural spectral continuity across formants.'
  },
  {
    module: 'prosody',
    name: 'Prosody & Pitch (F0) Contour Analysis',
    status: 'USED',
    direction: 'MIXED',
    contribution: 0.15,
    description: 'Pitch micro-jitter is flatter than natural human speech, suggesting neural vocoder output.'
  },
  {
    module: 'spectrogram',
    name: 'Spectrogram Anomaly / High-Frequency Filter',
    status: 'USED',
    direction: 'SUPPORTING',
    contribution: 0.12,
    description: 'High-frequency phase distortion observed above 7.2kHz characteristic of diffusion TTS.'
  },
  {
    module: 'whisper',
    name: 'Whisper Phonetic Consistency',
    status: 'USED',
    direction: 'SUPPORTING',
    contribution: 0.11,
    description: 'Phoneme transitions match expected acoustic pattern with minor temporal compression.'
  }
];

export const mockChunkTimeline: ChunkTimelineItem[] = [
  { chunkIndex: 0, startSec: 0.0, endSec: 5.0, decision: 'HUMAN', decisionStrength: -0.42, qualityScore: 0.91 },
  { chunkIndex: 1, startSec: 2.5, endSec: 7.5, decision: 'HUMAN', decisionStrength: -0.35, qualityScore: 0.89 },
  { chunkIndex: 2, startSec: 5.0, endSec: 10.0, decision: 'UNCERTAIN', decisionStrength: 0.08, qualityScore: 0.82 },
  { chunkIndex: 3, startSec: 7.5, endSec: 12.5, decision: 'AI_GENERATED', decisionStrength: 0.65, qualityScore: 0.88 },
  { chunkIndex: 4, startSec: 10.0, endSec: 15.0, decision: 'AI_GENERATED', decisionStrength: 0.82, qualityScore: 0.87 },
  { chunkIndex: 5, startSec: 12.5, endSec: 17.5, decision: 'AI_GENERATED', decisionStrength: 0.86, qualityScore: 0.85 },
];
